# Generated by Django 3.0.4 on 2020-06-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('team_id', models.IntegerField()),
                ('number', models.IntegerField()),
                ('player_nm', models.CharField(max_length=100)),
                ('player_kana', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('blood', models.CharField(max_length=2)),
                ('height', models.FloatField(max_length=3)),
                ('weight', models.FloatField(max_length=3)),
                ('hit_throw', models.CharField(max_length=2)),
                ('draft_year', models.IntegerField()),
                ('draft_rank', models.CharField(max_length=30)),
                ('join_year', models.IntegerField()),
                ('career', models.CharField(max_length=200)),
                ('award', models.CharField(max_length=200)),
                ('video', models.URLField(null=True)),
                ('img', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('team_nm', models.CharField(max_length=30)),
                ('league', models.CharField(max_length=1)),
                ('stadium', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50, null=True)),
                ('league_v', models.IntegerField()),
                ('japan_v', models.IntegerField()),
                ('owner', models.CharField(max_length=30)),
                ('img', models.TextField(null=True)),
                ('address_url', models.TextField(null=True)),
            ],
        ),
    ]
