# Generated by Django 3.0.4 on 2020-06-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='blood',
            field=models.CharField(max_length=10),
        ),
    ]
