# Generated by Django 3.0.4 on 2020-05-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_team_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
