# Generated by Django 3.0.4 on 2020-05-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20200506_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='team',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True, verbose_name='経度'),
        ),
    ]
