# Generated by Django 3.0.4 on 2020-05-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20200508_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lng',
        ),
        migrations.AddField(
            model_name='team',
            name='address_url',
            field=models.URLField(null=True),
        ),
    ]
