# Generated by Django 3.0.4 on 2020-05-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20200508_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='address_url',
            field=models.TextField(null=True),
        ),
    ]
