# Generated by Django 3.0.4 on 2020-05-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20200508_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
