# Generated by Django 3.0.4 on 2020-05-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_player_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
