# Generated by Django 3.0.4 on 2020-05-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20200511_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
