# Generated by Django 3.0.4 on 2020-05-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20200515_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.TextField(null=True),
        ),
    ]
