# Generated by Django 3.0.4 on 2020-05-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20200518_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='img',
            field=models.TextField(null=True),
        ),
    ]
